### ISSUE TITLE
Method not found errors from F# - GetMethod vs GetRuntimeMethods

### ISSUE THREAD

**Issue by AndrewIOM** [RandomEngy/PipeMethodCalls#10]
**What**
We are using the library in fslaborg/RProvider, with both F# Client and Server using a shared interface. 

**Steps to Reproduce**
From RProvider, change the dependency on PipeMethodCalls from my fork of PipeMethodCalls to the current published nuget package. Using this current PipeMethodCalls library results in an error: 'Method not found in interface IRInteropServer.'

**Possible Fix**
I forked this library and changed the call in PipeMethodCalls/RequestHandler/RequestHandler.cs from GetMethod() to GetRuntimeMethods(). The method is then discovered correctly.

**Comment by RandomEngy** [comment]
That method is a little slower but that's OK since both are plenty fast. Version 3.0.4 uses GetRuntimeMethods().

**Comment by AndrewIOM** [comment]
Thanks for the fix, and the library!
