### ISSUE TITLE
InvokeAsync hangs when using a function with > 1 argument in F# unless the args are tupled

### ISSUE THREAD

**Issue by ordinaryorange** [RandomEngy/PipeMethodCalls#12]
Was trying PipeMethodCalls in F#

An F# function handler with a single argument like this works
`use pipeServer = PipeServer (NetJsonPipeSerializer()) "mypipe" (fun a -> a)`
...
`use pipeClient = new PipeClient<int->int>(NetJsonPipeSerializer(), "mypipe")`

But the client will hang on `InvokeAnync` with this
`use pipeServer = PipeServer (NetJsonPipeSerializer()) "mypipe" (fun a b -> a+b)`
...
`use pipeClient = new PipeClient<int->int->int>(NetJsonPipeSerializer(), "mypipe")`

If I tuple the args, it works again.
`use pipeServer = PipeServer (NetJsonPipeSerializer()) "mypipe" (fun (a, b) -> a+b)`
...
`use pipeClient = new PipeClient<(int*int)->int>(NetJsonPipeSerializer(), "mypipe")`

The tuple is a workaround, but it would be nice for the former to work.

**Comment by RandomEngy** [comment]
I'm not very familiar with F# but it looks like you are passing in a function as the generic type parameter on PipeClient? That needs to be an interface type that represents which functions you can invoke.
