### ISSUE TITLE
Using ProtoBuf as binary serializer

### ISSUE THREAD

**Issue by tobe83** [RandomEngy/PipeMethodCalls#14]
Hello,
nice work with the PipeMethodCalls.

I want to use a binary serializer and so I made my own implementation with ProtoBuf:

```
public class ProtoBufPipeSerializer : IPipeSerializer
{
    public object Deserialize(byte[] data, Type type)
    {
	    using (var memoryStream = new MemoryStream())
	    {
		    memoryStream.Write(data, 0, data.Length);
		    return Serializer.Deserialize(type, memoryStream);
	    }
    }
    
    public byte[] Serialize(object o)
    {
	    using (var memoryStream = new MemoryStream())
	    {
		    Serializer.Serialize(memoryStream, o);
		    return memoryStream.ToArray();
	    }
    }
}

```
But this doesn't work.
What binary serializer do you recommend?

Cheers,
Tobias

**Comment by RandomEngy** [comment]
What protobuf NuGet package are you using? I think I remember seeing a fork that implemented a binary serializer but don't have time to check right now.

**Comment by tobe83** [comment]
this one here:
https://www.nuget.org/packages/protobuf-net/

**Comment by RandomEngy** [comment]
I tweaked your implementation a bit and got it working:

```cs
public object Deserialize(byte[] data, Type type)
{
	using (var memoryStream = new MemoryStream())
	{
		memoryStream.Write(data, 0, data.Length);
		memoryStream.Position = 0;
		return Serializer.Deserialize(type, memoryStream);
	}
}
```

You need to set position back to 0 in the `MemoryStream` for the deserializer to read the data.
