### ISSUE TITLE
NullReferenceException with MessagePackPipeSerializer and void methods

### ISSUE THREAD

**Issue by rseanhall** [RandomEngy/PipeMethodCalls#15]
Hi, thanks for the great work on PipeMethodCalls. I am trying to use an interface that looks like this:

```
public interface IClient
{
    void OnEventHappened();
}
```

This is resulting in a NullReferenceException from `o.GetType()` at https://github.com/RandomEngy/PipeMethodCalls/blob/a7629e75318d64a8068f3fba0f6e35443f634490/PipeMethodCalls.MessagePack/MessagePackPipeSerializer.cs#L20

This is my workaround for now, I haven't thought too hard about whether this would always work:

```
    public class MessagePackPipeSerializer : IPipeSerializer
    {
        public object? Deserialize(byte[] data, Type type)
        {
            if (data.Length == 0)
            {
                return null;
            }

            return MessagePackSerializer.Deserialize(type, data);
        }

        public byte[] Serialize(object? o)
        {
            if (o == null)
            {
                return Array.Empty<byte>();
            }

            return MessagePackSerializer.Serialize(o.GetType(), o);
        }
    }
```

**Comment by RandomEngy** [comment]
Thanks for the report! I think that workaround is solid. It looks like MessagePack serializes to arrays of at least 1 for any non-null value. At least it seems likely as an empty array and a `0` int both serialized to 1 byte. At any rate it will be less broken than it was!

https://github.com/RandomEngy/PipeMethodCalls/commit/2bd195d58825ab7813175aa775f379c18808b60d

**Comment by RandomEngy** [comment]
Released fix in PipeMethodCalls.MessagePack 3.0.1
