### ISSUE TITLE
Cannot send strings

### ISSUE THREAD

**Issue by WayneBBB** [RandomEngy/PipeMethodCalls#2]
Cannot set up PipeMethod to pass strings.  The pipeclient complained when I tried to set it up that I wasn't trying pass a string as a int.  Couldn't get around this when the code seemed to be oriented toward objects.     Methods aren't limited to int only.  The Readme.md wasn't clear about this limitation.

**Comment by RandomEngy** [comment]
I have a test app that works with strings as parameters. It should work with any built-in type. Can you post some example code that is not working for you?

**Comment by WayneBBB** [comment]
David:  I didn’t keep any of the code because I hadn’t gotten very far and I couldn’t see how to rectify the error after looking at some of the PipeMethods code.  Essentially what I assumed I had to do was substitute my own class into your examples.  For instance, in the below:

 

var pipeClient = new PipeClient<IAdder>("mypipe");

await pipeClient.ConnectAsync();

int result = await pipeClient.InvokeAsync(a => a.AddNumbers(1, 3));

 

I assumed I could use my own class/interface in place of IAdder and readdress the delegate (my class was basically a string property assigned a value through the constructor). Everything seemed to be coming together, except intellisence complained (naturally) about my string not being a int.  I assumed at that point that IAdder was tied in someway with the code.   Let me know  if I’m approaching this incorrectly and I’ll try it again.

**Comment by RandomEngy** [comment]
You can use your own interface in place of IAdder. I wouldn't recommend trying to use a concrete class there. You need to edit two places: `PipeClient<IYourInterface>` on the client side, and on the server side you provide an implementation of that interface:

`var pipeServer = new PipeServer<IYourInterface>("mypipe", () => new MyImplementation());`

Both the client and server should be referring to the same interface.

**Comment by WayneBBB** [comment]
I’ll try it tomorrow and let you know how it goes.  Thanks/Wayne

**Comment by WayneBBB** [comment]
I got problem one squared away.  Your example had the “result” as int, and I hadn’t changed it to string.  That is solved.  Now for the bigger issue.  I have set up two console apps (client/Server) as a means to see if I can get it working.  I don’t seem to understand how to use the program.  Here is some code that I hope you can point me in the right direction.  I keep getting the message back from both server/client: “System.Threading.Tasks.UnwrapPromise`1[System.Threading.Tasks.VoidTaskResult]”.   I have tried a number of things and nothing works.

 

namespace ClientPipeMethodCalls

{

    class Program

    {

        static void Main(string[] args)

        {

           Console.WriteLine("Input something to send a message to Server");

            

            string input=Console.ReadLine();

            //IPipeTypes tosend = new PipeTypes(input);

            var t = Task.Run(async () => 

            {

                var pipeClient = new PipeClient<IPipeTypes>("mypipe");

                await pipeClient.ConnectAsync();

                string result = await pipeClient.InvokeAsync(a =>a.ReturnType(input));

            } );

            Console.WriteLine("return from task was: " + t.ToString());

            Console.ReadLine();

        }

   }

}

 

The interface/class that is in both server and client

namespace ClientPipeMethodCalls

{

    interface IPipeTypes

    {

        string Command { get; set; }

        string ReturnType(string _cmd);

       

    } 

 

    

    class PipeTypes : IPipeTypes

    {

        public string Command { get; set; }

       

        public PipeTypes()

        {

 

        }

        public PipeTypes(string _cmd)

        {

            Command = _cmd;

        }

        public string ReturnType(string _cmd)

        {

            Command = _cmd;

           

            return Command;

        }

    }

}

 

Server code

namespace ServerPipeMethodCalls

{

    class Program

    {

        static void Main(string[] args)

        {

            //IPipeTypes newinput = new PipeTypes();

            var t = Task.Run(async()  => 

            {

                var pipeServer = new PipeServer<IPipeTypes>("mypipe", () => new PipeTypes());

                await pipeServer.WaitForConnectionAsync();

                string input= newinput.Command;

            });

            Console.WriteLine("var t from client is: " + t.ToString());

            Console.ReadLine();

        }

    }

}

**Comment by RandomEngy** [comment]
In ClientPipeMethodCalls, you want to print out result, not the task from your Task.Run wrapper.

As for your communication interface IPipeTypes, properties are not supported. Only methods. So get rid of the "Command" property. What are you trying to accomplish? I would start with something like this:

```
namespace ClientPipeMethodCalls
{
    class Program
    {
        static void Main(string[] args)
        {
           Console.WriteLine("Input something to send a message to Server");

            string input=Console.ReadLine();
            var t = Task.Run(async () =>
            {
                var pipeClient = new PipeClient<IPipeContract>("mypipe");
                await pipeClient.ConnectAsync();
                string result = await pipeClient.InvokeAsync(a =>a.ExecuteCommand(input));
                Console.WriteLine("return from task was: " + result);
            } );
            
            Console.ReadLine();
        }
   }
}


The interface/class that is in both server and client
namespace ClientPipeMethodCalls
{
    interface IPipeContract
    {
        string ExecuteCommand(string command);
    }
}

Server code
namespace ServerPipeMethodCalls
{
    class PipeImplementor : IPipeContract
    {
        public string ExecuteCommand(string command)
        {
            Console.WriteLine("Got command " + command);
            return command + " completed";
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var t = Task.Run(async()  =>
            {
                var pipeServer = new PipeServer<IPipeContract>("mypipe", () => new PipeImplementor());
                await pipeServer.WaitForConnectionAsync();
            });
            
            Console.ReadLine();
        }
    }
}
```

**Comment by WayneBBB** [comment]
Thanks Dave.  I now understand how it operates.  I did a Bi-Directional communications with success.  Thanks/Wayne
