### ISSUE TITLE
Friend, you are just a genius

### ISSUE THREAD

**Issue by RaySinner** [RandomEngy/PipeMethodCalls#23]
I've tried a dozen libraries, and **except for yours**, none of them work with complex scripts. My case is not a simple Blazor + lazy assembling (modules) of a third-party project. Some libraries do not parse assemblies correctly, some just freeze without errors, others do not have serialization of complex objects, others have old dependencies that conflict with already loaded assemblies. But your library just works out of the box. **Just out of the box!!!!!** I spent a week before finding your lib, and implemented duplex multi-client interaction in 20 minutes. **Thank you, you are a true friend! )))**

**Comment by RandomEngy** [comment]
Glad it's working for you!
