### ISSUE TITLE
Disconnects, seemingly, not detected.

### ISSUE THREAD

**Issue by LukeLonas** [RandomEngy/PipeMethodCalls#3]
I've been playing around with getting a simple client/server with callback, setup going.  I have my "server" running as a Windows service.  I'm able to make calls both directions, flawlessly.  My issue comes in when my "client" (UI application) goes away and the "server" (Win Service) keeps running.

I'm calling: `await pipeServer.WaitForRemotePipeCloseAsync(stoppingToken);`

However, this blocks forever.  It will even block long after the closure of the "client" application.  In addition to the library's way of detecting a closed pipe (`WaitForRemotePipeCloseAsync()`), I attempted a more manual approach of calling from the "server" to the "client" AFTER the "client" has disconnected in hopes of an error being thrown.  I made this call BEFORE the call to `WaitForRemotePipeCloseAsync()`, and it doesn't throw an exception.  Instead, this call seems to block forever.  Effectively, the status of my pipe seems to never get updated after being "connected".

Simplified example of my server code (Win Service):
```c#
while (!stoppingToken.IsCancellationRequested)
{
    var pipeServer = new PipeServerWithCallback<IUIController, IBackendController>(
        pipeName,
        () => new BackendController()
    );

    // Wait for pipe to be connected to.
    await pipeServer.WaitForConnectionAsync(stoppingToken);

    // Ask the UI to do some work.
    var result = await pipeServer.InvokeAsync(c => c.Foo(), stoppingToken);

    // Wait until somebody closes the pipe.
    await pipeServer.WaitForRemotePipeCloseAsync(stoppingToken);

    // Clean up
    pipeServer.Dispose();
}
```

Simplified example of my client code (UI application):
```c#
var pipeClient = new PipeClientWithCallback<IBackendController, IUIController>(
    pipeName,
    () => new UIController()
);

// Wait for pipe to be connected to.
await pipeClient.ConnectAsync();

// We're connected now.  Ask server to perform work.
var result = await pipeClient.InvokeAsync(s => s.Ping());

// Stay open for some time to allow processes to complete; then simulate UI shutdown
await Task.Delay(5000);

// Cleanup before we go away.
pipeClient.Dispose();
```

**Comment by RandomEngy** [comment]
Thanks for the report. This was a simple oversight in my conversion away from the "message" pipe format. I'll have a fix shortly.

**Comment by RandomEngy** [comment]
Should be fixed: https://www.nuget.org/packages/PipeMethodCalls/2.0.1

**Comment by LukeLonas** [comment]
Thanks for taking a look at that, appreciate it!
