### ISSUE TITLE
Allow for pipe security to be modified

### ISSUE THREAD

**Issue by LukeLonas** [RandomEngy/PipeMethodCalls#4]
I'm attempting to modify the named pipe security ACL.  In my case I want it to be more permissive.  I haven't found a way to access the underlying pipe to set the proper security description.  There are built-in methods for achieving this: [MS Docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipes.pipesaclextensions?view=netcore-3.1)

I can see two possible solutions to this:
1. Expose the underlying pipe instance so that the native methods can be used.
2. If there are concerns with exposing the entirety of the pipe instance - a wrapper could be devised that allows security values be read and updated.

I would love to see this added, and I'm happy to further discuss/contribute towards that goal.

**Comment by RandomEngy** [comment]
I'm thinking about it and it seems rather unlikely to me that I'm going to switch to using another API to implement this library, so exposing the raw pipe seems fine. Feel free to submit a PR.

**Comment by LukeLonas** [comment]
I've been playing with this today.  I hit a bit of snag with `SetAccessControl`.  It seems that .Net Core is unable to modify pipe security after creation.  Interestingly... .Net Framework seemingly had an overload when creating pipes to set the security up-front.  So, I don't know that I have a simple solution to this yet.  I would be happy to submit a PR if I solve this.

For reference and in-case you'd like to see a PR implementing part of what I was toying with, here are some notes on what I've found:

For exposing the pipe, I noticed you instantiate the actual raw named pipe when `WaitForConnectionAsync` is called.  I needed an opportunity to execute code on the instance of the raw pipe before the await is called, under the hood, so I solved this by allowing an optional `setupFunc` be passed into `WaitForConnectionAsync`.  If provided, it runs right before the await, and it passes the raw `NamedPipeServerStream` into the function.

There may still be value to a setup like this and/or just creating a public property that reflects the raw pipe.  Although there are issues setting security, you could still read the security values and/or do some more granular things with the actual pipe instance.

**Comment by RandomEngy** [comment]
The way I would probably try to tackle it would be to expose the "raw pipe" property, then create it early if some code tries to get it before connecting. That way you could create the client or server, then get the raw pipe before connecting and set your access control.

**Comment by LukeLonas** [comment]
Building off the PR I just submitted (#5) - I have devised a solution for setting pipe security that is working for me.  In .Net 5.0 the ability to construct a `NamedPipeServerStream` with `PipeSecurity` set has been fixed/readded.  What I've done is create an overloaded constructor for `PipeServer` and `PipeServerWithCallback` that just takes an existing named pipe and a handler function and "upgrades" it.

Attached below is an example of me implementing this change in my own code.  Would you be interested in a PR for this, as well?  It would satisfy this issue.  I think this provides the most flexibility and the idea of "upgrading" an existing named pipe into something that this library could handle seems like it has value.
![image](https://user-images.githubusercontent.com/16693361/98868564-919c4d00-242d-11eb-9cbe-136cc8ddb091.png)

**Comment by LukeLonas** [comment]
Resolved by #7 (continuation of work from #6)

**Comment by cbenard** [comment]
Thanks for doing 99% of that work @LukeLonas!

**Comment by LukeLonas** [comment]
@cbenard, no problem.  I'm happy to help.  Thanks putting the finishing touches on it.  I hope it works well for you!
